### ISSUE TITLE
yo jhipster-material - SyntaxError

### ISSUE THREAD

**Issue by toranaga** [hipster-labs/generator-jhipster-material#1]
mac, OS X
jhipster 3.4

yo jhipster-material

I'm getting:

/usr/local/lib/node_modules/generator-jhipster-material/generators/app/index.js:64
  configuring: {
  ^^^^^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.defineProperty.get [as jhipster-material:app](/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:260:16)

**Comment by deepu105** [comment]
Sorry this is still WIP
