### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by zpimak** [hipster-labs/generator-jhipster-material#2]
nodejs 6.2.1
npm 3.9.5
ubuntu.

/usr/lib/node_modules/generator-jhipster-material/generators/app/index.js:64
  configuring: {
  ^^^^^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.defineProperty.get [as jhipster-material:app](/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)

**Comment by osmarjunior** [comment]
The same here :(

**Comment by deepu105** [comment]
Its work in progress not ready for use yet.

**Comment by soyoeml** [comment]
Any progress please?
