### ISSUE TITLE
error while generating

### ISSUE THREAD

**Issue by TheCoder84** [hipster-labs/generator-jhipster-material#3]
when i run `yo jhipster-material` it gives error
```
/home/emre/.nvm/versions/node/v5.12.0/lib/node_modules/generator-jhipster-material/generators/app/index.js:64
  configuring: {
  ^^^^^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.defineProperty.get [as jhipster-material:app] (/home/emre/.nvm/versions/node/v5.12.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/home/emre/.nvm/versions/node/v5.12.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/home/emre/.nvm/versions/node/v5.12.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:262:16)
```

**Comment by deepu105** [comment]
its a WIP
