### ISSUE TITLE
 missing ) after argument list

### ISSUE THREAD

**Issue by giuliozelante** [hipster-labs/generator-jhipster-material#4]
##### **Overview of the issue**
I get this message when I launch the command **yo jhipster-material** 
```
C:\Users\utenteOrangee\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster-material\generators\app\index.js:64
  configuring: {
  ^^^^^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.get [as jhipster-material:app] (C:\Users\utenteOrangee\AppData\Local\Yarn\Data\global\node_modules\yeoman-environment\lib\store.js:39:27)

```
##### **Motivation for or Use Case** 

I can't use the generator at all

##### **JHipster Version(s)** 

I'm using JHipster v5.3.4

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

Nothing has been generated so....

##### **Browsers and Operating System** 

I'm using windows 10 Pro build 1803

##### **Reproduce the error** 

just launch the command specified at the start

**Comment by deepu105** [comment]
Sorry this repo is deprecated and will not work. I'll update the readme
